# Generated by Django 4.2.6 on 2023-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.UniqueConstraint(
                fields=("name", "acronym", "country"), name="unique_institution"
            ),
        ),
    ]
