# Generated by Django 4.2.6 on 2023-10-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_institution_unique_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children+",
                to="custom_user.institution",
            ),
        ),
    ]
