from .base import *


DEBUG = True
DEBUG404 = True
TEMPLATE_DEBUG = DEBUG
IS_TESTING = False

AXES_ENABLED = True


CSRF_USE_SESSIONS = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SECURE_HSTS_PRELOAD = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600
