from .base import *


DEBUG = True
DEBUG404 = True
TEMPLATE_DEBUG = DEBUG
IS_TESTING = False

AXES_ENABLED = True

SECURE_SSL_REDIRECT = True
CSRF_USE_SESSIONS = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
