# Generated by Django 4.2.6 on 2023-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsocialhistorydata",
            name="medical_drugs_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialhistorydata",
            name="medical_drugs_history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
