# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 17:05
from __future__ import unicode_literals

from django.db import migrations


def make_social_class_empty_if_it_is_null(apps, schema_editor):
    social_demographic_model = apps.get_model("patient", "socialdemographicdata")
    historical_social_demographic_model = apps.get_model(
        "patient", "historicalsocialdemographicdata"
    )

    for social_demographic in social_demographic_model.objects.all():
        if not social_demographic.social_class:
            social_demographic.social_class = ""
            social_demographic.save()

    for (
        historical_social_demographic
    ) in historical_social_demographic_model.objects.all():
        if not historical_social_demographic.social_class:
            historical_social_demographic.social_class = ""
            historical_social_demographic.save()


def make_social_class_null_if_it_is_empty(apps, schema_editor):
    social_demographic_model = apps.get_model("patient", "socialdemographicdata")
    historical_social_demographic_model = apps.get_model(
        "patient", "historicalsocialdemographicdata"
    )

    for social_demographic in social_demographic_model.objects.all():
        if social_demographic.social_class == "":
            social_demographic.social_class = None
            social_demographic.save()

    for (
        historical_social_demographic
    ) in historical_social_demographic_model.objects.all():
        if historical_social_demographic.social_class == "":
            historical_social_demographic.social_class = None
            historical_social_demographic.save()


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_auto_20190219_1243"),
    ]

    operations = [
        migrations.RunPython(
            make_social_class_empty_if_it_is_null, make_social_class_null_if_it_is_empty
        ),
    ]
