# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20190222_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='social_class',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='socialdemographicdata',
            name='social_class',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
