# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20190222_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhistorydata',
            name='alcohol_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.AlcoholFrequency'),
        ),
        migrations.AlterField(
            model_name='socialhistorydata',
            name='alcohol_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.AlcoholPeriod'),
        ),
        migrations.AlterField(
            model_name='socialhistorydata',
            name='amount_cigarettes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.AmountCigarettes'),
        ),
    ]
