# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20190313_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='is_completed',
            field=models.CharField(default='', max_length=50),
        ),
    ]
