# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_add_country_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
