# Generated by Django 2.2.28 on 2026-01-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20191125_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecorddata',
            options={'permissions': (('export_medicalrecorddata', 'Can export medical record'),)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (('export_patient', 'Can export patient'), ('sensitive_data_patient', 'Can view sensitive patient data'))},
        ),
        migrations.AlterModelOptions(
            name='questionnaireresponse',
            options={'permissions': (('export_questionnaireresponse', 'Can export questionnaire response'),)},
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='patient_schooling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient.Schooling', verbose_name='Schooling of the patient'),
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='schooling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient.Schooling', verbose_name='Schooling of the householder'),
        ),
    ]
