# Generated by Django 4.1.10 on 2023-08-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20191125_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient', 'verbose_name_plural': 'historical patients'},
        ),
        migrations.AlterModelOptions(
            name='historicalsocialdemographicdata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical social demographic data', 'verbose_name_plural': 'historical social demographic datas'},
        ),
        migrations.AlterModelOptions(
            name='historicalsocialhistorydata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical social history data', 'verbose_name_plural': 'historical social history datas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltelephone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical telephone', 'verbose_name_plural': 'historical telephones'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecorddata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionnaireresponse',
            options={},
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='patient_schooling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient.schooling', verbose_name='Schooling of the patient'),
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='schooling',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient.schooling', verbose_name='Schooling of the householder'),
        ),
        migrations.AlterField(
            model_name='historicalsocialhistorydata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltelephone',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
