# Generated by Django 2.2.28 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20260105_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
