# Generated by Django 3.2.25 on 2026-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20260105_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient', 'verbose_name_plural': 'historical patients'},
        ),
        migrations.AlterModelOptions(
            name='historicalsocialdemographicdata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical social demographic data', 'verbose_name_plural': 'historical social demographic datas'},
        ),
        migrations.AlterModelOptions(
            name='historicalsocialhistorydata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical social history data', 'verbose_name_plural': 'historical social history datas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltelephone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical telephone', 'verbose_name_plural': 'historical telephones'},
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialhistorydata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltelephone',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
