# Generated by Django 4.2.30 on 2026-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20260918_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocialdemographicdata',
            name='benefit_government',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialhistorydata',
            name='alcoholic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialhistorydata',
            name='ex_smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsocialhistorydata',
            name='smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialdemographicdata',
            name='benefit_government',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistorydata',
            name='alcoholic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistorydata',
            name='ex_smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistorydata',
            name='smoker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
