def set_limesurvey_api_mocks(mock_server):
    mock_server.return_value.get_session_key.return_value = 'idk208ghdkdg8bu'  # whatever string
    mock_server.return_value.get_survey_properties.return_value = {'language': 'en', 'additional_languages': ''}
    mock_server.return_value.export_responses.side_effect = [
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0'
        'aW9uZGF0ZSIsInN1YmplY3RpZCIsInExW1NRMDAxXSIsInExW1NRMDAyXSIsInEyIgoiMSIsIjE5ODAtMDEtMDEgMDA6MDA6MDAiLCIyI'
        'iwiZW4iLCJPU1NNYUZWZXdWbDhEMEoiLCIyIiwiMjAyMC0wOS0wNSAwMDowMDowMCIsIjk1OTE2IiwiQTEiLCJBMiIsIjQiCiIyIiwiMT'
        'k4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsImZGUG5Uc05VSndSeWUzZyIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTc'
        'iLCJBMiIsIkExIiwiMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0'
        'aW9uZGF0ZSIsInN1YmplY3RpZCIsInExW1NRMDAxXSIsInExW1NRMDAyXSIsInEyIgoiMSIsIjE5ODAtMDEtMDEgMDA6MDA6MDAiLCIyI'
        'iwiZW4iLCJPU1NNYUZWZXdWbDhEMEoiLCIyIiwiMjAyMC0wOS0wNSAwMDowMDowMCIsIjk1OTE2IiwiQTEiLCJBMiIsIjQiCiIyIiwiMT'
        'k4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsImZGUG5Uc05VSndSeWUzZyIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTc'
        'iLCJBMiIsIkExIiwiMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0'
        'aW9uZGF0ZSIsInN1YmplY3RpZCIsInExW1NRMDAxXSIsInExW1NRMDAyXSIsInEyIgoiMSIsIjE5ODAtMDEtMDEgMDA6MDA6MDAiLCIyI'
        'iwiZW4iLCJPU1NNYUZWZXdWbDhEMEoiLCIyIiwiMjAyMC0wOS0wNSAwMDowMDowMCIsIjk1OTE2IiwiQTEiLCJBMiIsIjQiCiIyIiwiMT'
        'k4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsImZGUG5Uc05VSndSeWUzZyIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTc'
        'iLCJBMiIsIkExIiwiMSIKCg=='
    ]
    mock_server.return_value.export_responses_by_token.side_effect = [
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0a'
        'W9uZGF0ZSIsInN1YmplY3RpZCIsInExIiwicTIiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsInNJYmozZ3dqdndwYT'
        'JRWSIsIjIiLCIyMDIwLTA5LTA1IDAwOjAwOjAwIiwiOTU5MTYiLCJhYmMiLCJBMSIKCg==',
    ]
    mock_server.return_value.list_groups.side_effect = \
        5 * [[
            {'id': {'gid': 1576, 'language': 'en'}, 'group_order': 1, 'randomization_group': '',
             'description': '', 'sid': 225461, 'gid': 1576, 'language': 'en', 'group_name': 'Identification',
             'grelevance': ''},
            {'id': {'gid': 1577, 'language': 'en'}, 'group_order': 2, 'randomization_group': '',
             'description': '', 'sid': 225461, 'gid': 1577, 'language': 'en', 'group_name': 'Grupo 1',
             'grelevance': ''},
        ]] + 5 * [[
            {'id': {'gid': 1578, 'language': 'en'}, 'group_order': 1, 'randomization_group': '', 'description': '',
             'sid': 888656, 'gid': 1578, 'language': 'en', 'group_name': 'Identification', 'grelevance': ''},
            {'id': {'gid': 1579, 'language': 'en'}, 'group_order': 2, 'randomization_group': '', 'description': '',
             'sid': 888656, 'gid': 1579, 'language': 'en', 'group_name': 'Grupo 1', 'grelevance': ''}
        ]] + 5 * [[
            {'id': {'gid': 1578, 'language': 'en'}, 'group_order': 1,
             'randomization_group': '', 'description': '',
             'sid': 888656, 'gid': 1578, 'language': 'en',
             'group_name': 'Identification', 'grelevance': ''},
            {'id': {'gid': 1579, 'language': 'en'}, 'group_order': 2,
             'randomization_group': '', 'description': '',
             'sid': 888656, 'gid': 1579, 'language': 'en',
             'group_name': 'Grupo 1', 'grelevance': ''}
        ]]

    mock_server.return_value.list_questions.side_effect = [
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3},
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3},
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3},
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None,
             'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1',
             'question_order': 3},
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579,
             'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None,
             'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ]
    ]
    mock_server.return_value.get_question_properties.side_effect = [
        {'other': 'N', 'attributes': {'hidn': '1'}, 'subquestions': 'No available answers', 'type': 'N',
         'question_order': 0, 'answeroptions': 'No available answer options', 'gid': 1576,
         'attributes_lang': 'No available attributes', 'title': 'responsibleid',
         'question': 'Responsible Identification number:'},
        {'other': 'N', 'attributes': {'hidden': '1'}, 'subquestions': 'No available answers', 'type': 'D',
         'question_order': 1, 'answeroptions': 'No available answer options', 'gid': 1576,
         'attributes_lang': 'No available attributes', 'title': 'acquisitiondate',
         'question': 'Acquisition date<strong>:</strong><br />\n'},
        {'other': 'N', 'attributes': {'hidden': '1'}, 'subquestions': 'No available answers', 'type': 'N',
         'question_order': 3, 'answeroptions': 'No available answer options', 'gid': 1576,
         'attributes_lang': 'No available attributes', 'title': 'subjectid',
         'question': 'Participant Identification number<b>:</b>'},
        {'other': 'N', 'attributes': 'No available attributes', 'subquestions': 'No available answers', 'type': 'T',
         'question_order': 1, 'answeroptions': 'No available answer options', 'gid': 1577,
         'attributes_lang': 'No available attributes', 'title': 'q1', 'question': 'Questão 1'},
        {'other': 'N', 'attributes': 'No available attributes', 'subquestions': 'No available answers', 'type': 'L',
         'question_order': 2,
         'answeroptions': {'A2': {'order': 2, 'assessment_value': 0, 'scale_id': 0, 'answer': 'Opção 2'},
                           'A1': {'order': 1, 'assessment_value': 0, 'scale_id': 0, 'answer': 'Opção 1'}}, 'gid': 1577,
         'attributes_lang': 'No available attributes', 'title': 'q2', 'question': 'Questão 2'},
        {'other': 'N', 'attributes': {'hidden': '1'}, 'subquestions': 'No available answers', 'type': 'N',
         'question_order': 0, 'answeroptions': 'No available answer options', 'gid': 1578,
         'attributes_lang': 'No available attributes', 'title': 'responsibleid',
         'question': 'Responsible Identification number:'},
        {'other': 'N', 'attributes': {'hidden': '1'}, 'subquestions': 'No available answers', 'type': 'D',
         'question_order': 1, 'answeroptions': 'No available answer options', 'gid': 1578,
         'attributes_lang': 'No available attributes', 'title': 'acquisitiondate',
         'question': 'Acquisition date<strong>:</strong><br />\n'},
        {'other': 'N', 'attributes': {'hidden': '1'}, 'subquestions': 'No available answers', 'type': 'N',
         'question_order': 3, 'answeroptions': 'No available answer options', 'gid': 1578,
         'attributes_lang': 'No available attributes', 'title': 'subjectid',
         'question': 'Participant Identification number<b>:</b>'},
        {'other': 'N', 'attributes': 'No available attributes',
         'subquestions': {'5016': {'scale_id': 0, 'title': 'SQ002', 'question': 'NoOk'},
                          '5015': {'scale_id': 0, 'title': 'SQ001', 'question': 'Ok'}}, 'type': 'F',
         'question_order': 1,
         'answeroptions': {'A2': {'order': 2, 'assessment_value': 0, 'scale_id': 0, 'answer': 'Opção 2'},
                           'A1': {'order': 1, 'assessment_value': 0, 'scale_id': 0, 'answer': 'Opção 1'}}, 'gid': 1579,
         'attributes_lang': 'No available attributes', 'title': 'q1', 'question': 'Questão 1'},
        {'other': 'N', 'attributes': 'No available attributes', 'subquestions': 'No available answers', 'type': 'T',
         'question_order': 1, 'answeroptions': 'No available answer options', 'gid': 1579,
         'attributes_lang': 'No available attributes', 'title': 'SQ001', 'question': 'Ok'},
        {'other': 'N', 'attributes': 'No available attributes', 'subquestions': 'No available answers', 'type': 'T',
         'question_order': 2, 'answeroptions': 'No available answer options', 'gid': 1579,
         'attributes_lang': 'No available attributes', 'title': 'SQ002', 'question': 'NoOk'},
        {'other': 'N', 'attributes': 'No available attributes', 'subquestions': 'No available answers', 'type': '5',
         'question_order': 3, 'answeroptions': 'No available answer options', 'gid': 1579,
         'attributes_lang': 'No available attributes', 'title': 'q2', 'question': 'Questão 2'}
    ]
    mock_server.return_value.get_participant_properties.side_effect = [
        {'token': 'sIbj3gwjvwpa2QY'}, {'token': 'OSSMaFVewVl8D0J'},
        {'token': 'sIbj3gwjvwpa2QY'}, {'token': 'WRFUAgTemzuu8nD'},
        {'token': 'OSSMaFVewVl8D0J'}, {'token': 'fFPnTsNUJwRye3g'},
        {'token': 'fFPnTsNUJwRye3g'}, {'token': 'fFPnTsNUJwRye3g'},
        {'token': 'fFPnTsNUJwRye3g'},
    ]
    mock_server.return_value.get_language_properties.side_effect = [
        {'surveyls_title': 'Admission Assessment Plugin'},
        {'surveyls_title': 'Surgical Evaluation Plugin'},
        {'surveyls_title': 'Follow-up Assessment Plugin'},
        {'surveyls_title': 'Admission Assessment Plugin'},
        {'surveyls_title': 'Surgical Evaluation Plugin'},
        {'surveyls_title': 'Follow-up Assessment Plugin'}
    ]


def update_limesurvey_api_mocks(mock_server):
    mock_server.return_value.list_questions.side_effect = [
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1', 'question_order': 3},
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3},
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5011,
             'mandatory': 'Y', 'other': 'N', 'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5011}, 'relevance': '1', 'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5012,
             'mandatory': 'Y', 'other': 'N', 'question': 'Acquisition date<strong>:</strong><br />\n', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5012}, 'relevance': '1', 'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1578, 'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5013, 'mandatory': 'Y',
             'other': 'N', 'question': 'Participant Identification number<b>:</b>', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5013}, 'relevance': '1', 'question_order': 3}
        ],
        [
            {'type': 'F', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 888656, 'modulename': None, 'parent_qid': 0, 'qid': 5014, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5014}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ001', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5015, 'mandatory': None,
             'other': 'N', 'question': 'Ok', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5015}, 'relevance': '1',
             'question_order': 1},
            {'type': 'T', 'same_default': 0, 'help': None, 'gid': 1579, 'preg': None, 'language': 'en',
             'title': 'SQ002', 'sid': 888656, 'modulename': None, 'parent_qid': 5014, 'qid': 5016, 'mandatory': None,
             'other': 'N', 'question': 'NoOk', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5016}, 'relevance': '',
             'question_order': 2},
            {'type': '5', 'same_default': 0, 'help': '', 'gid': 1579, 'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 888656, 'modulename': '', 'parent_qid': 0, 'qid': 5017, 'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0, 'id': {'language': 'en', 'qid': 5017}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3}
        ],
        [
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
        [
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'responsibleid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5006,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Responsible Identification number:', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5006}, 'relevance': '1',
             'question_order': 0},
            {'type': 'D', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'acquisitiondate', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5007,
             'mandatory': 'Y', 'other': 'N',
             'question': 'Acquisition date<strong>:</strong><br />\n',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5007}, 'relevance': '1',
             'question_order': 1},
            {'type': 'N', 'same_default': 0, 'help': '', 'gid': 1576,
             'preg': '', 'language': 'en',
             'title': 'subjectid', 'sid': 225461, 'modulename': None,
             'parent_qid': 0, 'qid': 5008, 'mandatory': 'Y',
             'other': 'N',
             'question': 'Participant Identification number<b>:</b>',
             'scale_id': 0,
             'id': {'language': 'en', 'qid': 5008}, 'relevance': '1',
             'question_order': 3},
            {'type': 'T', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q1',
             'sid': 225461, 'modulename': '', 'parent_qid': 0, 'qid': 5009,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 1', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5009}, 'relevance': '1',
             'question_order': 1},
            {'type': 'L', 'same_default': 0, 'help': '', 'gid': 1577,
             'preg': '', 'language': 'en', 'title': 'q2',
             'sid': 225461, 'modulename': None, 'parent_qid': 0, 'qid': 5010,
             'mandatory': 'N', 'other': 'N',
             'question': 'Questão 2', 'scale_id': 0,
             'id': {'language': 'en', 'qid': 5010}, 'relevance': '1',
             'question_order': 2}
        ],
    ]


def set_limesurvey_api_mocks2(mock_server):
    mock_server.return_value.get_survey_properties.side_effect = [
        {'additional_languages': 'pt-BR', 'language': 'en'},
        {'additional_languages': '', 'language': 'en'},
        {'additional_languages': 'pt-BR', 'language': 'en'},
        {'additional_languages': 'pt-BR', 'language': 'en'},
        {'additional_languages': '', 'language': 'en'},
        {'additional_languages': '', 'language': 'en'},
        {'additional_languages': 'pt-BR', 'language': 'en'},
        {'additional_languages': '', 'language': 'en'},
        {'additional_languages': 'pt-BR', 'language': 'en'},
    ]
    mock_server.return_value.export_responses.side_effect = [
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0aW9uZ'
        'GF0ZSIsInN1YmplY3RpZCIsInRleHRmcmFnZWVpbnMiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsIjE2TmhGaXpDNjhiVW'
        'h0VCIsIjIiLCIyMDIxLTA2LTA4IDAwOjAwOjAwIiwiNiIsIkFudHdvcnQgRWlucyIKCg==',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0aW9uZ'
        'GF0ZSIsInN1YmplY3RpZCIsInRleHRmcmFnZXp3ZWkiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsIll5VXpDdU5Uc25VMm'
        'N6ZSIsIjIiLCIyMDIxLTA2LTA4IDAwOjAwOjAwIiwiNiIsIkFudHdvcnQgWndlaSIKCg=='
    ]
    mock_server.return_value.export_responses_by_token.side_effect = [
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0aW9uZ'
        'GF0ZSIsInN1YmplY3RpZCIsInRleHRmcmFnZWVpbnMiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsIjE2TmhGaXpDNjhiVW'
        'h0VCIsIjIiLCIyMDIxLTA2LTA4IDAwOjAwOjAwIiwiNiIsIkFudHdvcnQgRWlucyIKCg ==',
        'IklEIGRhIHJlc3Bvc3RhIiwiRGF0YSBkZSBlbnZpbyIsIsOabHRpbWEgcMOhZ2luYSIsIklkaW9tYSBpbmljaWFsIiwiQ8OzZGlnbyBkZSBhY'
        '2Vzc28iLCJSZXNwb25zaWJsZSBJZGVudGlmaWNhdGlvbiBudW1iZXI6IiwiQWNxdWlzaXRpb24gZGF0ZToiLCJQYXJ0aWNpcGFudCBJZGVudG'
        'lmaWNhdGlvbiBudW1iZXI6IiwiVGV4dCBGcmFnZSBFaW5zIgoiMSIsIjE5ODAtMDEtMDEgMDA6MDA6MDAiLCIyIiwiZW4iLCIxNk5oRml6QzY'
        '4YlVodFQiLCIyIiwiMjAyMS0wNi0wOCAwMDowMDowMCIsIjYiLCJBbnR3b3J0IEVpbnMiCgo =',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0aW9uZ'
        'GF0ZSIsInN1YmplY3RpZCIsInRleHRmcmFnZXp3ZWkiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsIll5VXpDdU5Uc25VMm'
        'N6ZSIsIjIiLCIyMDIxLTA2LTA4IDAwOjAwOjAwIiwiNiIsIkFudHdvcnQgWndlaSIKCg ==',
        'IlJlc3BvbnNlIElEIiwiRGF0ZSBzdWJtaXR0ZWQiLCJMYXN0IHBhZ2UiLCJTdGFydCBsYW5ndWFnZSIsIlRva2VuIiwiUmVzcG9uc2libGUgS'
        'WRlbnRpZmljYXRpb24gbnVtYmVyOiIsIkFjcXVpc2l0aW9uIGRhdGU6IiwiUGFydGljaXBhbnQgSWRlbnRpZmljYXRpb24gbnVtYmVyOiIsIl'
        'RleHQgRnJhZ2UgWndlaSIKIjEiLCIxOTgwLTAxLTAxIDAwOjAwOjAwIiwiMiIsImVuIiwiWXlVekN1TlRzblUyY3plIiwiMiIsIjIwMjEtMDY'
        'tMDggMDA6MDA6MDAiLCI2IiwiQW50d29ydCBad2VpIgoK',
        'ImlkIiwic3VibWl0ZGF0ZSIsImxhc3RwYWdlIiwic3RhcnRsYW5ndWFnZSIsInRva2VuIiwicmVzcG9uc2libGVpZCIsImFjcXVpc2l0aW9uZ'
        'GF0ZSIsInN1YmplY3RpZCIsInRleHRmcmFnZWVpbnMiCiIxIiwiMTk4MC0wMS0wMSAwMDowMDowMCIsIjIiLCJlbiIsIjE2TmhGaXpDNjhiVW'
        'h0VCIsIjIiLCIyMDIxLTA2LTA4IDAwOjAwOjAwIiwiNiIsIkFudHdvcnQgRWlucyIKCg ==',
        'IklEIGRhIHJlc3Bvc3RhIiwiRGF0YSBkZSBlbnZpbyIsIsOabHRpbWEgcMOhZ2luYSIsIklkaW9tYSBpbmljaWFsIiwiQ8OzZGlnbyBkZSBhY'
        '2Vzc28iLCJSZXNwb25zaWJsZSBJZGVudGlmaWNhdGlvbiBudW1iZXI6IiwiQWNxdWlzaXRpb24gZGF0ZToiLCJQYXJ0aWNpcGFudCBJZGVudG'
        'lmaWNhdGlvbiBudW1iZXI6IiwiVGV4dCBGcmFnZSBFaW5zIgoiMSIsIjE5ODAtMDEtMDEgMDA6MDA6MDAiLCIyIiwiZW4iLCIxNk5oRml6QzY'
        '4YlVodFQiLCIyIiwiMjAyMS0wNi0wOCAwMDowMDowMCIsIjYiLCJBbnR3b3J0IEVpbnMiCgo =',
    ]
    mock_server.return_value.list_groups.side_effect = [
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1961, 'sid': 689143, 'group_name': 'Identification',
          'id': {'gid': 1961, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1962, 'sid': 689143, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1962, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1961, 'sid': 689143, 'group_name': 'Identification',
          'id': {'gid': 1961, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1962, 'sid': 689143, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1962, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1961, 'sid': 689143, 'group_name': 'Identification',
          'id': {'gid': 1961, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1962, 'sid': 689143, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1962, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2},
         {'grelevance': '', 'gid': 1959, 'sid': 798261, 'group_name': 'Identification',
          'id': {'gid': 1959, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '', 'language': 'pt-BR',
          'group_order': 1}, {'grelevance': '', 'gid': 1960, 'sid': 798261, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1960, 'language': 'pt-BR'}, 'description': '', 'randomization_group': '',
                              'language': 'pt-BR', 'group_order': 2}],
        [{'grelevance': '', 'gid': 1961, 'sid': 689143, 'group_name': 'Identification',
          'id': {'gid': 1961, 'language': 'en'}, 'description': '', 'randomization_group': '', 'language': 'en',
          'group_order': 1}, {'grelevance': '', 'gid': 1962, 'sid': 689143, 'group_name': 'Gruppe Eins',
                              'id': {'gid': 1962, 'language': 'en'}, 'description': '', 'randomization_group': '',
                              'language': 'en', 'group_order': 2}]
    ]
    mock_server.return_value.list_questions.side_effect = [
        [{'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en', 'gid': 1959,
          'qid': 7938, 'sid': 798261, 'title': 'subjectid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7938}, 'preg': '', 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1959,
          'qid': 7937, 'sid': 798261, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7937}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1959, 'qid': 7936,
          'sid': 798261, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7936}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Eins',
          'type': 'S', 'language': 'en', 'gid': 1960, 'qid': 7939, 'sid': 798261, 'title': 'textfrageeins',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7939}, 'preg': '',
          'question_order': 1}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Eins',
          'type': 'S', 'language': 'en', 'gid': 1960, 'qid': 7939, 'sid': 798261, 'title': 'textfrageeins',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7939}, 'preg': '',
          'question_order': 1}, {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
                                 'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en',
                                 'gid': 1959, 'qid': 7938, 'sid': 798261, 'title': 'subjectid', 'modulename': None,
                                 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7938}, 'preg': '',
                                 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1959,
          'qid': 7937, 'sid': 798261, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7937}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1959, 'qid': 7936,
          'sid': 798261, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7936}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Eins',
          'type': 'S', 'language': 'en', 'gid': 1960, 'qid': 7939, 'sid': 798261, 'title': 'textfrageeins',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7939}, 'preg': '',
          'question_order': 1}, {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
                                 'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en',
                                 'gid': 1959, 'qid': 7938, 'sid': 798261, 'title': 'subjectid', 'modulename': None,
                                 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7938}, 'preg': '',
                                 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1959,
          'qid': 7937, 'sid': 798261, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7937}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1959, 'qid': 7936,
          'sid': 798261, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7936}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en', 'gid': 1961,
          'qid': 7942, 'sid': 689143, 'title': 'subjectid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7942}, 'preg': '', 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1961,
          'qid': 7941, 'sid': 689143, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7941}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1961, 'qid': 7940,
          'sid': 689143, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7940}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Zwei',
          'type': 'S', 'language': 'en', 'gid': 1962, 'qid': 7943, 'sid': 689143, 'title': 'textfragezwei',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7943}, 'preg': '',
          'question_order': 1}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Zwei',
          'type': 'S', 'language': 'en', 'gid': 1962, 'qid': 7943, 'sid': 689143, 'title': 'textfragezwei',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7943}, 'preg': '',
          'question_order': 1}, {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
                                 'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en',
                                 'gid': 1961, 'qid': 7942, 'sid': 689143, 'title': 'subjectid', 'modulename': None,
                                 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7942}, 'preg': '',
                                 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1961,
          'qid': 7941, 'sid': 689143, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7941}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1961, 'qid': 7940,
          'sid': 689143, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7940}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en', 'gid': 1959,
          'qid': 7938, 'sid': 798261, 'title': 'subjectid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7938}, 'preg': '', 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1959,
          'qid': 7937, 'sid': 798261, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7937}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1959, 'qid': 7936,
          'sid': 798261, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7936}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Eins',
          'type': 'S', 'language': 'en', 'gid': 1960, 'qid': 7939, 'sid': 798261, 'title': 'textfrageeins',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7939}, 'preg': '',
          'question_order': 1}],
        [{'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Participant Identification number<b>:</b>', 'type': 'N', 'language': 'en', 'gid': 1961,
          'qid': 7942, 'sid': 689143, 'title': 'subjectid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7942}, 'preg': '', 'question_order': 3},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Acquisition date<strong>:</strong><br />\n', 'type': 'D', 'language': 'en', 'gid': 1961,
          'qid': 7941, 'sid': 689143, 'title': 'acquisitiondate', 'modulename': None, 'relevance': '1',
          'same_default': 0, 'id': {'language': 'en', 'qid': 7941}, 'preg': '', 'question_order': 1},
         {'other': 'N', 'help': '', 'mandatory': 'Y', 'scale_id': 0, 'parent_qid': 0,
          'question': 'Responsible Identification number:', 'type': 'N', 'language': 'en', 'gid': 1961, 'qid': 7940,
          'sid': 689143, 'title': 'responsibleid', 'modulename': None, 'relevance': '1', 'same_default': 0,
          'id': {'language': 'en', 'qid': 7940}, 'preg': '', 'question_order': 0}],
        [{'other': 'N', 'help': '', 'mandatory': 'N', 'scale_id': 0, 'parent_qid': 0, 'question': 'Text Frage Zwei',
          'type': 'S', 'language': 'en', 'gid': 1962, 'qid': 7943, 'sid': 689143, 'title': 'textfragezwei',
          'modulename': None, 'relevance': '1', 'same_default': 0, 'id': {'language': 'en', 'qid': 7943}, 'preg': '',
          'question_order': 1}]
    ]
    mock_server.return_value.get_question_properties.side_effect = [
        {'question': 'Text Frage Eins', 'title': 'textfrageeins', 'answeroptions': 'No available answer options',
         'subquestions': 'No available answers', 'question_order': 1, 'attributes': 'No available attributes',
         'gid': 1960, 'attributes_lang': 'No available attributes', 'other': 'N', 'type': 'S'},
        {'question': 'Participant Identification number<b>:</b>', 'title': 'subjectid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 3,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
        {'question': 'Acquisition date<strong>:</strong><br />\n', 'title': 'acquisitiondate',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 1,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'D'},
        {'question': 'Responsible Identification number:', 'title': 'responsibleid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 0,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
        {'question': 'Text Frage Eins', 'title': 'textfrageeins', 'answeroptions': 'No available answer options',
         'subquestions': 'No available answers', 'question_order': 1, 'attributes': 'No available attributes',
         'gid': 1960, 'attributes_lang': 'No available attributes', 'other': 'N', 'type': 'S'},
        {'question': 'Participant Identification number<b>:</b>', 'title': 'subjectid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 3,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
        {'question': 'Acquisition date<strong>:</strong><br />\n', 'title': 'acquisitiondate',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 1,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'D'},
        {'question': 'Responsible Identification number:', 'title': 'responsibleid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 0,
         'attributes': {'hidden': '1'}, 'gid': 1959, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
        {'question': 'Text Frage Zwei', 'title': 'textfragezwei', 'answeroptions': 'No available answer options',
         'subquestions': 'No available answers', 'question_order': 1, 'attributes': 'No available attributes',
         'gid': 1962, 'attributes_lang': 'No available attributes', 'other': 'N', 'type': 'S'},
        {'question': 'Participant Identification number<b>:</b>', 'title': 'subjectid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 3,
         'attributes': {'hidden': '1'}, 'gid': 1961, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
        {'question': 'Acquisition date<strong>:</strong><br />\n', 'title': 'acquisitiondate',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 1,
         'attributes': {'hidden': '1'}, 'gid': 1961, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'D'},
        {'question': 'Responsible Identification number:', 'title': 'responsibleid',
         'answeroptions': 'No available answer options', 'subquestions': 'No available answers', 'question_order': 0,
         'attributes': {'hidden': '1'}, 'gid': 1961, 'attributes_lang': 'No available attributes', 'other': 'N',
         'type': 'N'},
    ]
    mock_server.return_value.get_participant_properties.side_effect = [
        {'token': '16NhFizC68bUhtT'},
        {'token': 'YyUzCuNTsnU2cze'},
        {'token': '16NhFizC68bUhtT'},
        {'token': '16NhFizC68bUhtT'},
        {'token': 'YyUzCuNTsnU2cze'},
        {'token': '16NhFizC68bUhtT'},
        {'token': 'YyUzCuNTsnU2cze'}
    ]
    mock_server.return_value.get_language_properties.side_effect = [
        {'surveyls_title': 'Questionário simples um'},
        {'surveyls_title': 'Einfacher Fragebogen Zwei'},
        {'surveyls_title': 'Einfacher Fragebogen Eins'},
        {'surveyls_title': 'Questionário simples um'},
        {'surveyls_title': 'Einfacher Fragebogen Zwei'},
        {'surveyls_title': 'Questionário simples um'},
    ]
