# Generated by Django 4.2.6 on 2023-10-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("lime_survey_id", models.IntegerField(unique=True)),
                ("is_initial_evaluation", models.BooleanField(default=True)),
                ("pt_title", models.CharField(default=None, max_length=255, null=True)),
                ("en_title", models.CharField(default=None, max_length=255, null=True)),
                ("is_active", models.BooleanField(null=True)),
            ],
            options={
                "permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SensitiveQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=150)),
                ("question", models.TextField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_questions",
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "unique_together": {("survey", "code")},
            },
        ),
    ]
