# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('lime_survey_id', models.IntegerField(unique=True)),
                ('is_initial_evaluation', models.BooleanField(default=True)),
                ('pt_title', models.CharField(default=None, max_length=255, null=True)),
                ('en_title', models.CharField(default=None, max_length=255, null=True)),
                ('is_active', models.NullBooleanField(default=None)),
            ],
            options={
                'permissions': (('view_survey', 'Can view survey'),),
            },
        ),
        migrations.AddField(
            model_name='sensitivequestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_questions', to='survey.Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='sensitivequestion',
            unique_together=set([('survey', 'code')]),
        ),
    ]
