# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="en_title",
            field=models.CharField(null=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="survey",
            name="pt_title",
            field=models.CharField(null=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(null=True, default=None),
        ),
    ]
