# Generated by Django 2.2.28 on 2026-01-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190401_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
    ]
