# Generated by Django 4.1.10 on 2023-08-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_auto_20190401_1335"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={},
        ),
        migrations.AlterField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
