# Generated by Django 4.2.4 on 2023-08-29 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import export.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "input_file",
                    models.FileField(
                        max_length=1000, upload_to=export.models.get_export_dir
                    ),
                ),
                (
                    "output_export",
                    models.FileField(
                        max_length=1000, upload_to=export.models.get_export_dir
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
