# Generated by Django 4.2.6 on 2023-10-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomForests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_url", models.CharField(default="", max_length=200)),
                (
                    "admission_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_admission",
                        to="survey.survey",
                    ),
                ),
                (
                    "followup_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_followup",
                        to="survey.survey",
                    ),
                ),
                (
                    "surgical_evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_surgical",
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_send_data_to_plugin", "Can send data to plugin"),
                ),
            },
        ),
    ]
