# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 13:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("survey", "0002_auto_20190401_1335"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomForests",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_admission",
                        to="survey.Survey",
                    ),
                ),
                (
                    "surgical_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_surgical",
                        to="survey.Survey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
