# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-21 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomForests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_url', models.CharField(default='', max_length=200)),
                ('admission_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_admission', to='survey.Survey')),
                ('followup_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_followup', to='survey.Survey')),
                ('surgical_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_surgical', to='survey.Survey')),
            ],
            options={
                'permissions': (('can_send_data_to_plugin', 'Can send data to plugin'),),
            },
        ),
    ]
