# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 18:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plugin", "0002_auto_20190513_1424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="randomforests",
            name="admission_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_admission",
                to="survey.Survey",
            ),
        ),
        migrations.AlterField(
            model_name="randomforests",
            name="surgical_evaluation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_surgical",
                to="survey.Survey",
            ),
        ),
    ]
