# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plugin", "0003_auto_20190514_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomforests",
            name="plugin_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
