# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-31 19:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_auto_20190401_1335"),
        ("plugin", "0004_randomforests_plugin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomforests",
            name="followup_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_followup",
                to="survey.Survey",
            ),
        ),
    ]
