# Generated by Django 4.2.6 on 2023-10-11 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localinstitution",
            options={"verbose_name": "Local Institution"},
        ),
    ]
