# Generated by Django 4.2.6 on 2023-10-14 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_alter_localinstitution_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact"},
        ),
        migrations.AlterModelOptions(
            name="rightssupport",
            options={
                "managed": False,
                "permissions": [("upgrade_rights", "Can upgrade NES version")],
            },
        ),
    ]
