# Generated by Django 4.2.6 on 2023-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0003_alter_contact_options_alter_rightssupport_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("url", models.URLField()),
            ],
        ),
    ]
